Controllers/AssetController.cs
using MobileReimbursement.BusinessClass;
using MobileReimbursement.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using System.Configuration;

namespace MobileReimbursement.Controllers
{
    public class AssetController : Controller
    {
        private DatabaseRepository dr = new DatabaseRepository();

        public void DataTableColumnRename(DataTable dt, Dictionary<string, string> d)
        {
            foreach (KeyValuePair<string, string> pair in d)
            {
                dt.Columns[pair.Key].ColumnName = pair.Value;
            }
        }

        private IQueryable<T> SortIQueryableFileData<T>(IQueryable<T> data, string fieldName, string sortOrder)
        {
            if (string.IsNullOrWhiteSpace(fieldName)) return data;
            if (string.IsNullOrWhiteSpace(sortOrder)) return data;

            var param = System.Linq.Expressions.Expression.Parameter(typeof(T), "i");
            System.Linq.Expressions.Expression conversion = System.Linq.Expressions.Expression.Convert(System.Linq.Expressions.Expression.Property(param, fieldName), typeof(object));
            var mySortExpression = System.Linq.Expressions.Expression.Lambda<Func<T, object>>(conversion, param);

            return (sortOrder == "desc") ? data.OrderByDescending(mySortExpression)
                : data.OrderBy(mySortExpression);
        }

        public ActionResult MobileMaster()
        {
            return View();
        }

        public ActionResult ReimbursementClaim()
        {
            return View();
        }

        public ActionResult ReimbursementApproval()
        {
            int status = -1;
            string returnmessage = "";

            dr = new DatabaseRepository();
            DataTable dtTable = new DataTable();
            asset_report objasset_report = new asset_report();

            try
            {
                //objasset_report.Status = Request.QueryString["status"];
                objasset_report.FromDate = !string.IsNullOrEmpty(Request.QueryString["fdate"]) ? Convert.ToString(Request.QueryString["fdate"]) : string.Empty;
                objasset_report.ToDate   = !string.IsNullOrEmpty(Request.QueryString["tdate"]) ? Convert.ToString(Request.QueryString["tdate"]) : string.Empty;

                dtTable = dr.AssetRequestStatus(objasset_report, out status, out returnmessage);

                if (dtTable.Rows.Count > 0)
                {
                    Response.ClearContent();
                    Response.ContentType = "application/vnd.ms-excel";
                    Response.AddHeader("Content-Disposition", "inline; filename=AssetRequestStatus.xls"); // Download File Name.
                    Response.Write("<table border='1 px' style='width: 941px; cellspacing=0 frame=void rules=none border-color: #C0C0C0;'><tr style='background-color: #FFFFCC'>");

                    for (int i = 0; i < dtTable.Columns.Count; i++)
                    {
                        Response.Write("<td style='height: 22px; font-weight: lighter; background-color: lightcyan; text-align: center;'>");
                        Response.Write(dtTable.Columns[i].ColumnName.ToString());
                        Response.Write("</span></td>");
                    }
                    Response.Write("</tr>");
                    for (int i = 0; i < dtTable.Rows.Count; i++)
                    {
                        Response.Write("<tr>");
                        for (int j = 0; j < dtTable.Columns.Count; j++)
                        {
                            Response.Write("<td style='height: 22px;'>" + dtTable.Rows[i][j].ToString() + " </td>");
                        }
                        Response.Write("</tr>");
                    }
                    Response.Write("</table>");
                    Response.End();
                    status = 0;
                }
            }
            catch
            {
            }
            return View();
        }

        public ActionResult MonthlyReport()
        {
            return View();
        }

        public ActionResult DepartmentwiseReport()
        {
            int status = -1;
            string returnmessage = "";

            dr = new DatabaseRepository();
            DataTable dtTable = new DataTable();
            asset_report objasset_report = new asset_report();

            try
            {
                objasset_report.Status = Request.QueryString["status"];
                objasset_report.FromDate = !string.IsNullOrEmpty(Request.QueryString["fdate"]) ? Convert.ToString(Request.QueryString["fdate"]) : string.Empty;
                objasset_report.ToDate   = !string.IsNullOrEmpty(Request.QueryString["tdate"]) ? Convert.ToString(Request.QueryString["tdate"]) : string.Empty;

                dtTable = dr.DownloadReport(objasset_report, out status, out returnmessage);

                if (dtTable.Rows.Count > 0)
                {
                    Response.ClearContent();
                    Response.ContentType = "application/vnd.ms-excel";
                    Response.AddHeader("Content-Disposition", "inline; filename=AssetReport.xls"); // Download File Name.
                    Response.Write("<table border='1 px' style='width: 941px; cellspacing=0 frame=void rules=none border-color: #C0C0C0;'><tr style='background-color: #FFFFCC'>");

                    for (int i = 0; i < dtTable.Columns.Count; i++)
                    {
                        Response.Write("<td style='height: 22px; font-weight: lighter; background-color: lightcyan; text-align: center;'>");
                        Response.Write(dtTable.Columns[i].ColumnName.ToString());
                        Response.Write("</span></td>");
                    }
                    Response.Write("</tr>");
                    for (int i = 0; i < dtTable.Rows.Count; i++)
                    {
                        Response.Write("<tr>");
                        for (int j = 0; j < dtTable.Columns.Count; j++)
                        {
                            Response.Write("<td style='height: 22px;'>" + dtTable.Rows[i][j].ToString() + " </td>");
                        }
                        Response.Write("</tr>");
                    }
                    Response.Write("</table>");
                    Response.End();
                    status = 0;
                }
            }
            catch
            {
            }
            return View();
        }

        public ActionResult selfRequest()
        {
            dr = new DatabaseRepository();
            DataTable dtTable = new DataTable();

            dtTable = dr.GetHOD();

            var a = (from d in dtTable.AsEnumerable()
                     select new AssetComman
                     {
                         HOD = d.Field<dynamic>("HOD")
                     }).FirstOrDefault();
            ViewBag.hod = a.HOD;

            return View();
        }

        [HttpPost]
        public JsonResult GetItem()
        {
            var objStatusList = new List<dropdown>();
            dr = new DatabaseRepository();
            DataTable dtTable = dr.GetItem();
            objStatusList = new List<dropdown>(dtTable.Rows.Count);

            foreach (DataRow row in dtTable.Rows)
            {
                var obj = new dropdown()
                {
                    Drpvalu = row["NTYPECODE"] != null ? Convert.ToString(row["NTYPECODE"]) : "0",
                    Drptext = row["VTYPEDESCRIPTION"] != null ? Convert.ToString(row["VTYPEDESCRIPTION"]) : string.Empty
                };
                objStatusList.Add(obj);
            }

            var jsonResult = Json(objStatusList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }

        public ActionResult NewJoiner()
        {
            return View();
        }

        [HttpPost]
        public JsonResult GetCompany()
        {
            var objStatusList = new List<dropdown>();
            dr = new DatabaseRepository();
            DataTable dtTable = dr.GetCompany();
            objStatusList = new List<dropdown>(dtTable.Rows.Count);

            foreach (DataRow row in dtTable.Rows)
            {
                var obj = new dropdown()
                {
                    Drpvalu = row["COMPANY"] != null ? Convert.ToString(row["COMPANY"]) : "0",
                    Drptext = row["CMPNAME"] != null ? Convert.ToString(row["CMPNAME"]) : string.Empty
                };
                objStatusList.Add(obj);
            }

            var jsonResult = Json(objStatusList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }

        [HttpPost]
        //public JsonResult GetDivision(int? CompanyID)
        public JsonResult GetDivision(string CompanyID)
        {
            if (!string.IsNullOrEmpty(CompanyID))
            {
                var objStatusList = new List<dropdown>();
                dr = new DatabaseRepository();
                DataTable dtTable = dr.GetDivision(CompanyID);
                objStatusList = (from a in dtTable.AsEnumerable()
                                 select new dropdown
                                 {
                                     Drpvalu = a.Field<dynamic>("DIVISION") != null ? Convert.ToString(a.Field<dynamic>("DIVISION")) : 0,
                                     Drptext = a.Field<dynamic>("DIVNAME") != null ? Convert.ToString(a.Field<dynamic>("DIVNAME")) : string.Empty,
                                 }).ToList();
                var jsonResult = Json(objStatusList, JsonRequestBehavior.AllowGet);

Views/Asset/DepartmentwiseReport.cshtml
@{
    ViewBag.Title = Layout;
}
<script type="text/javascript">
   
</script>
@using (Html.BeginForm("DownloadReport", "Asset", FormMethod.Post, new { name = "frm_AssetReport", id = "frm_AssetReport", novalidate = "novalidate", @class = "form-horizontal" }))
{
    <div class="widget-box col-sm-12">
        <div class="widget-header widget-header-flat">
            <h4 class="widget-title smaller">
                <i class="ace-icon fa fa-list-alt smaller-120"></i>Mobile Reimbursement Report
            </h4>
        </div>
        <div class="widget-body">
            <div class="widget-main">

                <div class="form-group">
                    <label class="control-label control-label-left col-sm-3" for="txt_LicenseproductName">Department:</label>
                    <div class="controls col-sm-3">
                        <select id="drp_Month" name="drp_Month" class="select2 form-control" data-parsley-errors-container="#errId1" data-placeholder="Click to Choose Month..." aria-hidden="true">
                            <option value="">--Select--</option>
                            <option value="01">Finance</option>
                            <option value="02">Chemical SBU</option>
                            <option value="03">Taxation</option>
                            <option value="04">Marketing</option>
                            <option value="05">IT</option>
                            <option value="06">Purchase</option>
                        </select>

                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-xs-12 col-sm-3 no-padding-right" for="drp_status">Departmentwise Report Status : </label>

                    <div class="col-xs-12 col-sm-5">
                        <div class="clearfix">
                            <select id="drp_status" name="drp_status" class="select2 col-xs-12 col-sm-9" data-placeholder="Click to Choose Asset Status..." aria-hidden="true">
                                <option value="3">All</option>
                                <option value="1">Active</option>
                                <option value="2">Allocated</option>
                            </select>
                        </div>
                    </div>
                </div>

                <div class="form-group" id="div_fdate">
                    <label class="control-label col-xs-12 col-sm-3 no-padding-right">From Date : </label>

                    <div class="col-xs-12 col-sm-5">
                        <div class="clearfix">
                            <input class="date-picker col-xs-12 col-sm-9" id="txt_fromdate" name="txt_fromdate" type="text" data-date-format="dd-M-yyyy" value="">
                            <span class="badge badge-yellow" style="margin-left: 15px;"><span title="" class="ace-icon fa fa-question gray" data-rel="tooltip" data-placement="right" data-original-title="Enter From Date in DD/MM/YYYY format"></span></span>
                        </div>
                    </div>
                </div>

                <div class="form-group" id="div_tdate">
                    <label class="control-label col-xs-12 col-sm-3 no-padding-right">To Date : </label>

                    <div class="col-xs-12 col-sm-5">
                        <div class="clearfix">
                            <input class="date-picker col-xs-12 col-sm-9" id="txt_todate" name="txt_todate" type="text" data-date-format="dd-M-yyyy" value="">
                            <span class="badge badge-yellow" style="margin-left: 15px;"><span title="" class="ace-icon fa fa-question gray" data-rel="tooltip" data-placement="right" data-original-title="Enter To Date in DD/MM/YYYY format"></span></span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-xs-12 col-sm-12" style="text-align: center;">
                        <div class="clearfix">
                            <button id="btn_download" name="btn_download" type="submit" class="btn btn-success btn-next" data-last="Finish" onclick="SubmitRequest();"><i class="ace-icon fa fa-file-excel-o icon-on-right"></i>&nbsp; Download</button>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
}
<script>
    $(document).ready(function () {
        $("[data-rel=tooltip]").tooltip(); $('.date-picker').datepicker({ autoclose: true, todayHighlight: true }).next().on(ace.click_event, function () { $(this).prev().focus(); });
        $(".date-picker").datepicker("setDate", new Date());
    });
</script>

Views/Asset/FSAssetReport.cshtml
@{
    ViewBag.Title = Layout;
}
<script type="text/javascript">
    //$(document).ready(function () {
    //    $("#drp_status").change(function () {
    //        var val = $("#drp_status").val();
    //        if (val != "2") {
    //            $("#div_fdate").hide();
    //            $("#div_tdate").hide();
    //        } else {
    //            $("#div_fdate").show();
    //            $("#div_tdate").show();
    //        }
    //    });
    //});
    $.validator.addMethod("reqtxt_fromdate", function (value, element) {
        if ($("#drp_status").val() == "2") {
            if ($("#txt_fromdate").val().length <= 0)
                return false;
            else
                return true;
        }
        else {
            return true;
        }
    }, 'Please Enter From Date.');
    $.validator.addMethod("reqtxt_todate", function (value, element) {
        if ($("#drp_status").val() == "2") {
            if ($("#txt_todate").val().length <= 0)
                return false;
            else
                return true;
        }
        else {
            return true;
        }
    }, 'Please Enter To Date.');
    $.validator.addMethod("reqtwo_date", function (value, element) {
        if ($("#txt_fromdate").val().length > $("#txt_todate").val().length)
            return false;
        else
            return true;
    }, 'To date must be less then from date');
    function SubmitRequest() {
        var formid = 'frm_AssetReport';
        var obj = validateForm(formid);
        if (obj.form()) {
            var objurl = '@Url.Content("~/Asset/FSAssetReport")';
            objurl += "?status=" + $("#drp_status").val() + "&fdate=" + $("#txt_fromdate").val() + "&tdate=" + $("#txt_todate").val()
            window.open(objurl);
            return false;
        }
        else {
            return false;
        }
    }
    function validateForm(formid) {
        return $("#" + formid).validate({
            errorElement: 'div',
            errorClass: 'help-block',
            focusInvalid: false,
            ignore: "",
            rules: {
                txt_fromdate: {
                    reqtxt_fromdate: true
                },
                txt_todate: {
                    reqtxt_todate: true
                }
            },
            messages: {
            },

            highlight: function (e) {
                $(e).closest('.form-group').removeClass('has-info').addClass('has-error');
            },

            success: function (e) {
                $(e).closest('.form-group').removeClass('has-error'); //.addClass('has-info');
                $(e).remove();
            },

            errorPlacement: function (error, element) {
                if (element.is('input[type=checkbox]') || element.is('input[type=radio]')) {
                    var controls = element.closest('div[class*="col-"]');
                    if (controls.find(':checkbox,:radio').length > 1) controls.append(error);
                    else error.insertAfter(element.nextAll('.lbl:eq(0)').eq(0));
                }
                else if (element.is('.select2')) {
                    error.insertAfter(element.siblings('[class*="select2-container"]:eq(0)'));
                }
                else if (element.is('.chosen-select')) {
                    error.insertAfter(element.siblings('[class*="chosen-container"]:eq(0)'));
                }
                else error.insertAfter(element.parent());
            },

            submitHandler: function (form) {
            },
            invalidHandler: function (form) {
            }
        });
    }
</script>
@using (Html.BeginForm("FSAssetReport", "Asset", FormMethod.Post, new { name = "frm_AssetReport", id = "frm_AssetReport", novalidate = "novalidate", @class = "form-horizontal" }))
{
    <div class="widget-box col-sm-12">
        <div class="widget-header widget-header-flat">
            <h4 class="widget-title smaller">
                <i class="ace-icon fa fa-list-alt smaller-120"></i>FS Asset Report
            </h4>
        </div>
        <div class="widget-body">
            <div class="widget-main">

                @*<div class="form-group">
                        <label class="control-label col-xs-12 col-sm-3 no-padding-right" for="drp_status">Asset Status : </label>

                        <div class="col-xs-12 col-sm-5">
                            <div class="clearfix">
                                <select id="drp_status" name="drp_status" class="select2 col-xs-12 col-sm-9" data-placeholder="Click to Choose Asset Status..." aria-hidden="true">
                                    <option value="3">All</option>
                                    <option value="1">Active</option>
                                    <option value="2">Allocated</option>
                                </select>
                            </div>
                        </div>
                    </div>*@

                <div class="form-group" id="div_fdate">
                    <label class="control-label col-xs-12 col-sm-3 no-padding-right">From Date : </label>

                    <div class="col-xs-12 col-sm-5">
                        <div class="clearfix">
                            <input class="date-picker col-xs-12 col-sm-9" id="txt_fromdate" name="txt_fromdate" type="text" data-date-format="dd-M-yyyy" value="">
                            <span class="badge badge-yellow" style="margin-left: 15px;"><span title="" class="ace-icon fa fa-question gray" data-rel="tooltip" data-placement="right" data-original-title="Enter From Date in DD/MM/YYYY format"></span></span>
                        </div>
                    </div>
                </div>

                <div class="form-group" id="div_tdate">
                    <label class="control-label col-xs-12 col-sm-3 no-padding-right">To Date : </label>

                    <div class="col-xs-12 col-sm-5">
                        <div class="clearfix">
                            <input class="date-picker col-xs-12 col-sm-9" id="txt_todate" name="txt_todate" type="text" data-date-format="dd-M-yyyy" value="">
                            <span class="badge badge-yellow" style="margin-left: 15px;"><span title="" class="ace-icon fa fa-question gray" data-rel="tooltip" data-placement="right" data-original-title="Enter To Date in DD/MM/YYYY format"></span></span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-xs-12 col-sm-12" style="text-align: center;">
                        <div class="clearfix">
                            <button id="btn_download" name="btn_download" type="submit" class="btn btn-success btn-next" data-last="Finish" onclick="SubmitRequest();"><i class="ace-icon fa fa-file-excel-o icon-on-right"></i>&nbsp; Download</button>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
}
<script>
    $(document).ready(function () {
        $("[data-rel=tooltip]").tooltip(); $('.date-picker').datepicker({ autoclose: true, todayHighlight: true }).next().on(ace.click_event, function () { $(this).prev().focus(); });
        $(".date-picker").datepicker("setDate", new Date());
    });
</script>

Views/Asset/MonthlyReport.cshtml
@{
    ViewBag.Title = Layout;
}
<script type="text/javascript">
   
</script>
@using (Html.BeginForm("DownloadReport", "Asset", FormMethod.Post, new { name = "frm_AssetReport", id = "frm_AssetReport", novalidate = "novalidate", @class = "form-horizontal" }))
{
    
    <div class="widget-box col-sm-12">
        <div class="widget-header widget-header-flat">
            <h4 class="widget-title smaller">
                <i class="ace-icon fa fa-list-alt smaller-120"></i>Mobile Reimbursement Report
            </h4>
        </div>
        <div class="widget-body">
            <div class="widget-main">

                <div class="form-group">
                    <label class="control-label col-xs-12 col-sm-3 no-padding-right" for="drp_status">Monthly Report Status : </label>

                    <div class="col-xs-12 col-sm-5">
                        <div class="clearfix">
                            <select id="drp_status" name="drp_status" class="select2 col-xs-12 col-sm-9" data-placeholder="Click to Choose Asset Status..." aria-hidden="true">
                                <option value="3">All</option>
                                <option value="1">Active</option>
                                <option value="2">Allocated</option>
                            </select>
                        </div>
                    </div>
                </div>

                <div class="form-group" id="div_fdate">
                    <label class="control-label col-xs-12 col-sm-3 no-padding-right">From Date : </label>

                    <div class="col-xs-12 col-sm-5">
                        <div class="clearfix">
                            <input class="date-picker col-xs-12 col-sm-9" id="txt_fromdate" name="txt_fromdate" type="text" data-date-format="dd-M-yyyy" value="">
                            <span class="badge badge-yellow" style="margin-left: 15px;"><span title="" class="ace-icon fa fa-question gray" data-rel="tooltip" data-placement="right" data-original-title="Enter From Date in DD/MM/YYYY format"></span></span>
                        </div>
                    </div>
                </div>

                <div class="form-group" id="div_tdate">
                    <label class="control-label col-xs-12 col-sm-3 no-padding-right">To Date : </label>

                    <div class="col-xs-12 col-sm-5">
                        <div class="clearfix">
                            <input class="date-picker col-xs-12 col-sm-9" id="txt_todate" name="txt_todate" type="text" data-date-format="dd-M-yyyy" value="">
                            <span class="badge badge-yellow" style="margin-left: 15px;"><span title="" class="ace-icon fa fa-question gray" data-rel="tooltip" data-placement="right" data-original-title="Enter To Date in DD/MM/YYYY format"></span></span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-xs-12 col-sm-12" style="text-align: center;">
                        <div class="clearfix">
                            <button id="btn_download" name="btn_download" type="submit" class="btn btn-success btn-next" data-last="Finish" onclick="SubmitRequest();"><i class="ace-icon fa fa-file-excel-o icon-on-right"></i>&nbsp; Download</button>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
}
<script>
    $(document).ready(function () {
        $("[data-rel=tooltip]").tooltip(); $('.date-picker').datepicker({ autoclose: true, todayHighlight: true }).next().on(ace.click_event, function () { $(this).prev().focus(); });
        $(".date-picker").datepicker("setDate", new Date());
    });
</script>